#默认使用配置
spring:
  profiles:
    active: dev

server:
  port: 8080

---

#开发配置
spring:
  profiles: dev
  application:
    name: service-gateway
  session:
    timeout: 86400
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
  # redis 配置
  redis:
    port: 6379
    host: 123.57.29.205
    database: 0
    password: DavidLiu7
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.31.212:8849
        namespace: ldw
    gateway:
      routes:
        - id: trace-user
          uri: lb://trace-user
          predicates:
            - Path=/api/user/**
        - id: trace-post
          uri: lb://trace-post
          predicates:
            - Path=/api/post/**
        - id: trace-feed
          uri: lb://trace-feed
          predicates:
            - Path=/api/feed/**
        - id: trace-oss
          uri: lb://trace-oss
          predicates:
            - Path=/api/oss/**
        - id: trace-sms
          uri: lb://trace-sms
          predicates:
            - Path=/api/sms/**
      globalcors:
        cors-configurations:
          '[/**]':
            #            allowedOrigins: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 360000
        add-to-simple-url-handler-mapping: true  # 解决option的跨域问题
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
#server:
#  netty:
#    connection-timeout: 10000