server:
  port: 8081
spring:
  application:
    name: tracenote
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.29.205:3306/tracenote?useSSL=false&serverTimezone=UTC
    username: root
    password: DavidLiu7
  rabbitmq:
    host: 123.57.29.205
    port: 5672
    username: david
    password: DavidLiu7
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 5000ms
          multiplier: 2
  redis:
    host: 123.57.29.205
    port: 6379
#    password: DavidLiu7
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: cn.neud.trace.note.entity # 别名扫描包
logging:
  level:
    cn.neud.trace.note: debug
  pattern:
    dateformat: mm:ss.SSS